version: "3"

services:
  webserver:
    build:
        context: ./www
    dns:
      8.8.8.8
    ports:
       - "80:80"
    environment:
     - APACHE_RUN_USER=#1000
     - TERM=xterm-256color
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
